services:
  web:
    build: .
    ports:
      - "8000:5000"
    restart: always

  redis:
    image: "redis:alpine"
  
  backend:
    image: imageName
    ports:
      - "9090:8080"
    restart: always